server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9949
    gateway:
      routes:
        - id: pms-service
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-service
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-service
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: oms-service
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: wms-service
          uri: lb://wms-service
          predicates:
            - Path=/wms/**