logging:
  level:
    com.atguigu: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
spring:
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge