server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9949
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.116.100:3306/guli_ums
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  global-config:
    db-config:
      id-type: auto
